### ISSUE TITLE
Problem running raw-data script

### ISSUE THREAD

**Issue by dkwik** [sadleskorn/apply303#3]
Hey @EleanorLee42  @sadleskorn , im having a problem running the raw-data script which has stunted any progress on this project for me. I keep getting this error:

Error in read.dcf(con) : Line starting '<<<<<<< HEAD ...' is malformed!

I'll ask Prof. Pruim tomorrow, but for now please be patient with me!

**Comment by EleanorLee42** [comment]
We fixed this by deleting the sus lines!
